### ISSUE TITLE
Postmatic is not installed message

### ISSUE THREAD

**Issue by Vernal** [JeffMatson/postmatic-gf#1]
In 4.4 and with Postmatic 2 beta this nag shows up on the admin:
_Postmatic is not installed or activated! You will need to install and activate Postmatic before using this plugin!_

**Comment by cyberhobo** [comment]
@Vernal, can you try this again with the current beta? I can't reproduce it.

**Comment by JeffMatson** [comment]
Yeah, I wasn't able to replicate either.

**Comment by JeffMatson** [comment]
Oh wait, beta. Disregard. Haven't tested with it.

**Comment by Vernal** [comment]
Can't replicate. Closing.
